name: Neprekinjena integracija

on: # Kdaj se začne izvajanje delovnega toka?
  push:
    branches:
      - main # Ob vsaki uveljavitvi na veji main.
    paths-ignore:
      - "README.md" # Ignoriramo spremembe v dokumentaciji.

jobs:
  build:
    runs-on: # Okolje, v katerem se testi izvedejo.
      - ubuntu-latest
    strategy:
      matrix:
        node-verzija:
        #   - 12.x
          - 18.x
        steps: # Posamezni koraki testiranja.
          - uses: actions/checkout@v2 # Pridobimo izvorno kodo repozitorija.
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x' # replace with your Python version
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt # replace with your requirements file if you have one
          - name: Start Server
            run: |
              python backend.py &
              sleep 5 # wait for the server to start
          - name: Uporabi Node.js 18.x # Nastavi Node.js okolje.
            uses: actions/setup-node@v1
            with:
              node-version: 18.x
          - run: npm install # Namesti knjižnice.
          - run: npm test # Poženi teste.